# Generated by Django 4.2 on 2026-04-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=120, verbose_name='Empresa / Instituição')),
                ('role', models.CharField(max_length=120, verbose_name='Cargo / Curso')),
                ('exp_type', models.CharField(choices=[('trabalho', 'Trabalho'), ('educacao', 'Educação')], default='trabalho', max_length=10, verbose_name='Tipo')),
                ('start_date', models.DateField(verbose_name='Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Término')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('is_current', models.BooleanField(default=False, verbose_name='Emprego/curso atual?')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Experiência',
                'verbose_name_plural': 'Experiências',
                'ordering': ['-is_current', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Título')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug (URL)')),
                ('description', models.TextField(verbose_name='Descrição curta')),
                ('details', models.TextField(blank=True, verbose_name='Detalhes completos')),
                ('status', models.CharField(choices=[('concluido', 'Concluído'), ('andamento', 'Em andamento'), ('academico', 'Acadêmico')], default='concluido', max_length=15, verbose_name='Status')),
                ('tech_stack', models.CharField(blank=True, max_length=255, verbose_name='Stack (separado por vírgula)')),
                ('github_url', models.URLField(blank=True, verbose_name='Link GitHub')),
                ('demo_url', models.URLField(blank=True, verbose_name='Link Demo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('featured', models.BooleanField(default=False, verbose_name='Destaque?')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['order', '-featured'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nome')),
                ('category', models.CharField(choices=[('linguagem', 'Linguagem'), ('framework', 'Framework / Biblioteca'), ('banco', 'Banco de Dados'), ('infra', 'Infraestrutura'), ('ferramenta', 'Ferramenta'), ('ia', 'IA / LLM')], max_length=20, verbose_name='Categoria')),
                ('level', models.PositiveSmallIntegerField(default=3, verbose_name='Nível (1–5)')),
                ('icon', models.CharField(blank=True, max_length=30, verbose_name='Ícone (emoji ou classe CSS)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
